#include "raylib.h"
#include "raymath.h"
#include "nlohmann/json.hpp"  // Include nlohmann/json for JSON parsing. Install via vcpkg: vcpkg install nlohmann-json
#include <fstream>
#include <string>
#include <vector>

// Game states
enum GameState { STATE_MENU, STATE_GAME };

void DrawMenu(int screenWidth, int screenHeight) {
    DrawText("CS 3 AI", screenWidth / 2 - MeasureText("CS 3 AI", 40) / 2, screenHeight / 2 - 50, 40, BLACK);
    DrawText("Press ENTER to START", screenWidth / 2 - MeasureText("Press ENTER to START", 20) / 2, screenHeight / 2, 20, GRAY);
}

std::vector<std::vector<int>> LoadMap() {
    std::ifstream file("map.json");
    std::vector<std::vector<int>> map;
    if (file.is_open()) {
        std::string content((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
        auto json = nlohmann::json::parse(content);
        for (auto& row : json) {
            std::vector<int> rowVec;
            for (auto& cell : row) {
                rowVec.push_back(cell);
            }
            map.push_back(rowVec);
        }
    }
    return map;
}

void GenerateLevel(std::vector<Model>& walls, const std::vector<std::vector<int>>& map) {
    walls.clear();
    for (size_t i = 0; i < map.size(); ++i) {
        for (size_t j = 0; j < map[i].size(); ++j) {
            if (map[i][j] == 1) {
                Model wall = LoadModelFromMesh(GenMeshCube(1.0f, 4.0f, 1.0f));
                walls.push_back(wall);
                // Position walls at (j*2, 2, i*2) for spacing
                // Note: Adjust positions as needed
            }
        }
    }
}

int main() {
    // Initialize window
    const int screenWidth = 1280;
    const int screenHeight = 720;
    InitWindow(screenWidth, screenHeight, "CS 3 AI");
    SetTargetFPS(60);

    // Game state
    GameState currentState = STATE_MENU;

    // Define the camera to look into our 3D world
    Camera camera = { 0 };
    camera.position = (Vector3){ 0.0f, 2.0f, 4.0f };    // Camera position
    camera.target = (Vector3){ 0.0f, 2.0f, 0.0f };      // Camera looking at point
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };          // Camera up vector
    camera.fovy = 60.0f;                                 // Camera field-of-view Y
    camera.projection = CAMERA_PERSPECTIVE;              // Camera projection type

    // Player movement variables
    Vector3 playerPosition = { 0.0f, 2.0f, 4.0f };
    float playerSpeed = 5.0f;
    float mouseSensitivity = 0.003f;
    Vector2 mouseDelta = { 0.0f, 0.0f };

    // Load textures (replace with your image paths)
    // Texture2D groundTexture = LoadTexture("ground.png");
    Texture2D wallTexture = LoadTexture("wall_texture.png");  // Generated by Python
    Texture2D botTexture = LoadTexture("bot_texture.png");    // Load bot texture

    // Simple ground
    Model ground = LoadModelFromMesh(GenMeshPlane(20.0f, 20.0f, 1, 1));
    // ground.materials[0].maps[MATERIAL_MAP_DIFFUSE].texture = groundTexture;

    // Load map and generate level
    auto mapData = LoadMap();
    std::vector<Model> walls;
    GenerateLevel(walls, mapData);
    for (auto& wall : walls) {
        wall.materials[0].maps[MATERIAL_MAP_DIFFUSE].texture = wallTexture;
    }

    // Bot model (cube with texture)
    Model bot = LoadModelFromMesh(GenMeshCube(1.0f, 2.0f, 1.0f));
    bot.materials[0].maps[MATERIAL_MAP_DIFFUSE].texture = botTexture;

    while (!WindowShouldClose()) {
        if (currentState == STATE_MENU) {
            // Menu logic
            if (IsKeyPressed(KEY_ENTER)) {
                currentState = STATE_GAME;
                DisableCursor();  // Lock cursor for 3D game
            }
            // Draw menu
            BeginDrawing();
                ClearBackground(WHITE);
                DrawMenu(screenWidth, screenHeight);
            EndDrawing();
        } else if (currentState == STATE_GAME) {
            // Update camera position based on player movement
            camera.position = playerPosition;

            // Mouse look
            mouseDelta = GetMouseDelta();
            camera.target.x += mouseDelta.x * mouseSensitivity;
            camera.target.y += mouseDelta.y * mouseSensitivity;

            // WASD movement
            if (IsKeyDown(KEY_W)) playerPosition.z -= playerSpeed * GetFrameTime();
            if (IsKeyDown(KEY_S)) playerPosition.z += playerSpeed * GetFrameTime();
            if (IsKeyDown(KEY_A)) playerPosition.x -= playerSpeed * GetFrameTime();
            if (IsKeyDown(KEY_D)) playerPosition.x += playerSpeed * GetFrameTime();

            // Shooting with raycast (left mouse button)
            if (IsMouseButtonPressed(MOUSE_BUTTON_LEFT)) {
                Ray ray = GetMouseRay(GetMousePosition(), camera);
                // Perform raycast against models or scene
                // For demo, just print hit position
                TraceLog(LOG_INFO, "Shot fired from (%.2f, %.2f, %.2f) to (%.2f, %.2f, %.2f)",
                         playerPosition.x, playerPosition.y, playerPosition.z,
                         ray.direction.x, ray.direction.y, ray.direction.z);
            }

            // Read bot status from bot_status.json
            Vector3 botPosition = { 0.0f, 1.0f, -5.0f };  // Default
            std::ifstream file("bot_status.json");
            if (file.is_open()) {
                std::string content((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
                auto json = nlohmann::json::parse(content);
                // Read bot position
                if (json.contains("position")) {
                    botPosition.x = json["position"]["x"];
                    botPosition.y = json["position"]["y"];
                    botPosition.z = json["position"]["z"];
                }
                if (json.contains("action")) {
                    std::string action = json["action"];
                    TraceLog(LOG_INFO, "Bot action: %s", action.c_str());
                }
            }

            // Draw
            BeginDrawing();
                ClearBackground(RAYWHITE);

                BeginMode3D(camera);
                    // Draw ground
                    DrawModel(ground, (Vector3){0.0f, 0.0f, 0.0f}, 1.0f, GRAY);
                    // Draw walls from map
                    int index = 0;
                    for (size_t i = 0; i < mapData.size(); ++i) {
                        for (size_t j = 0; j < mapData[i].size(); ++j) {
                            if (mapData[i][j] == 1) {
                                DrawModel(walls[index], (Vector3){(float)j * 2.0f - 10.0f, 2.0f, (float)i * 2.0f - 10.0f}, 1.0f, WHITE);
                                index++;
                            }
                        }
                    }
                    // Draw bot
                    DrawModel(bot, botPosition, 1.0f, WHITE);
                EndMode3D();

                DrawFPS(10, 10);
            EndDrawing();
        }
    }

    // Unload textures
    // UnloadTexture(groundTexture);
    UnloadTexture(wallTexture);
    UnloadTexture(botTexture);

    UnloadModel(ground);
    for (auto& wall : walls) UnloadModel(wall);
    UnloadModel(bot);

    CloseWindow();
    return 0;
}