name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create external directory
      run: |
        New-Item -ItemType Directory -Force -Path external
        New-Item -ItemType Directory -Force -Path external/hllib

    - name: Download HLLib sources
      run: git clone https://github.com/syndetic-networks/hllib.git external/hllib

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Test
      run: cd build && ctest --output-on-failure