name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Checkout raylib
      uses: actions/checkout@v4
      with:
        repository: raysan5/raylib
        path: external/raylib

    - name: Checkout nlohmann/json
      uses: actions/checkout@v4
      with:
        repository: nlohmann/json
        path: external/json

    - name: Checkout HLLib
      uses: actions/checkout@v4
      with:
        repository: nemysis/hllib
        path: external/hllib

    - name: Checkout Bullet
      uses: actions/checkout@v4
      with:
        repository: bulletphysics/bullet3
        path: external/bullet3

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Test
      run: cd build && ctest --output-on-failure

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cs3_exe
        path: build/Release/cs3_ai.exe